### ISSUE TITLE
Blink should only fire over certain animations

### ISSUE THREAD

**Issue by jake** [totallyviable/ok-dracula#41]
add a check in BlinkAnimation to only fire if the animation is currently playing from a list of acceptable animations 

-----

barely digging into this, but it seems like since the BootyBounce animation manipulates the face, when the Blink animation plays on its own track they both play.

maybe has to do with how the face animation swaps? could definitely be doing the blink cycle wrong, as well.

![sep-15-2016 10-42-35](https://cloud.githubusercontent.com/assets/285917/18554096/2354f7b0-7b31-11e6-9ab2-39cb1a5cab83.gif)

**Comment by psql** [comment]
Ya. So 'blink' should never occur, while bootyBounce happens. But booty bounce can be additive with walk & idle

**Comment by jake** [comment]
ahhh, ok. so its kinda just designed to be mutually exclusive?

**Comment by psql** [comment]
@jake yeah. Maybe we can come up with a matrix of additive animation vs mutually exclusive?
A......... spreadsheet?

**Comment by jake** [comment]
fixed! can now specify which base animations the blink can play over. 

![screen shot 2016-09-16 at 1 36 48 am](https://cloud.githubusercontent.com/assets/285917/18576274/115894b8-7bae-11e6-9ffb-e3bd97b493e3.png)
